name: Update WakaTime Data

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:        # Allows you to manually trigger the workflow

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # or use a version that supports your setup

      - name: Install Dependencies
        run: npm install

      - name: Update WakaTime Data
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: node scripts/update_wakatime.js

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'static/wakatime.json'
          message: 'Update WakaTime data [skip ci]'
